// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.3
// source: common/event.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type       string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	RootID     string `protobuf:"bytes,3,opt,name=RootID,proto3" json:"RootID,omitempty"`
	RootType   string `protobuf:"bytes,4,opt,name=RootType,proto3" json:"RootType,omitempty"`
	ParentID   string `protobuf:"bytes,5,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	ParentType string `protobuf:"bytes,6,opt,name=ParentType,proto3" json:"ParentType,omitempty"`
}

func (x *EventHeader) Reset() {
	*x = EventHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventHeader) ProtoMessage() {}

func (x *EventHeader) ProtoReflect() protoreflect.Message {
	mi := &file_common_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventHeader.ProtoReflect.Descriptor instead.
func (*EventHeader) Descriptor() ([]byte, []int) {
	return file_common_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventHeader) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *EventHeader) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventHeader) GetRootID() string {
	if x != nil {
		return x.RootID
	}
	return ""
}

func (x *EventHeader) GetRootType() string {
	if x != nil {
		return x.RootType
	}
	return ""
}

func (x *EventHeader) GetParentID() string {
	if x != nil {
		return x.ParentID
	}
	return ""
}

func (x *EventHeader) GetParentType() string {
	if x != nil {
		return x.ParentType
	}
	return ""
}

type DLQHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic      string            `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Partition  int64             `protobuf:"varint,2,opt,name=Partition,proto3" json:"Partition,omitempty"`
	Offset     int64             `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
	GroupID    string            `protobuf:"bytes,4,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	Headers    map[string]string `protobuf:"bytes,5,rep,name=Headers,proto3" json:"Headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RetryCount int64             `protobuf:"varint,10,opt,name=RetryCount,proto3" json:"RetryCount,omitempty"`
}

func (x *DLQHeader) Reset() {
	*x = DLQHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DLQHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DLQHeader) ProtoMessage() {}

func (x *DLQHeader) ProtoReflect() protoreflect.Message {
	mi := &file_common_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DLQHeader.ProtoReflect.Descriptor instead.
func (*DLQHeader) Descriptor() ([]byte, []int) {
	return file_common_event_proto_rawDescGZIP(), []int{1}
}

func (x *DLQHeader) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *DLQHeader) GetPartition() int64 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *DLQHeader) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DLQHeader) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *DLQHeader) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *DLQHeader) GetRetryCount() int64 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

type EventReprocess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Topic     string `protobuf:"bytes,2,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Partition int64  `protobuf:"varint,3,opt,name=Partition,proto3" json:"Partition,omitempty"`
	Offset    int64  `protobuf:"varint,4,opt,name=Offset,proto3" json:"Offset,omitempty"`
}

func (x *EventReprocess) Reset() {
	*x = EventReprocess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_event_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventReprocess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReprocess) ProtoMessage() {}

func (x *EventReprocess) ProtoReflect() protoreflect.Message {
	mi := &file_common_event_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReprocess.ProtoReflect.Descriptor instead.
func (*EventReprocess) Descriptor() ([]byte, []int) {
	return file_common_event_proto_rawDescGZIP(), []int{2}
}

func (x *EventReprocess) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *EventReprocess) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *EventReprocess) GetPartition() int64 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *EventReprocess) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_common_event_proto protoreflect.FileDescriptor

var file_common_event_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0xa1, 0x01, 0x0a,
	0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x52, 0x6f, 0x6f, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x6f, 0x6f, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x44,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x44,
	0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x87, 0x02, 0x0a, 0x09, 0x44, 0x4c, 0x51, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x44, 0x12, 0x38, 0x0a, 0x07, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x44,
	0x4c, 0x51, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x52, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x52, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x3a,
	0x0a, 0x0c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x6c, 0x0a, 0x0e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x70,
	0x69, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x79, 0x65, 0x72, 0x79, 0x61, 0x6e, 0x2f, 0x6c,
	0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x6f, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_event_proto_rawDescOnce sync.Once
	file_common_event_proto_rawDescData = file_common_event_proto_rawDesc
)

func file_common_event_proto_rawDescGZIP() []byte {
	file_common_event_proto_rawDescOnce.Do(func() {
		file_common_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_event_proto_rawDescData)
	})
	return file_common_event_proto_rawDescData
}

var file_common_event_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_event_proto_goTypes = []interface{}{
	(*EventHeader)(nil),    // 0: common.EventHeader
	(*DLQHeader)(nil),      // 1: common.DLQHeader
	(*EventReprocess)(nil), // 2: common.EventReprocess
	nil,                    // 3: common.DLQHeader.HeadersEntry
}
var file_common_event_proto_depIdxs = []int32{
	3, // 0: common.DLQHeader.Headers:type_name -> common.DLQHeader.HeadersEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_event_proto_init() }
func file_common_event_proto_init() {
	if File_common_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DLQHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_event_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventReprocess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_event_proto_goTypes,
		DependencyIndexes: file_common_event_proto_depIdxs,
		MessageInfos:      file_common_event_proto_msgTypes,
	}.Build()
	File_common_event_proto = out.File
	file_common_event_proto_rawDesc = nil
	file_common_event_proto_goTypes = nil
	file_common_event_proto_depIdxs = nil
}
