// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.3
// source: luser/service.proto

package luser

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserCreationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MCC         string `protobuf:"bytes,1,opt,name=MCC,proto3" json:"MCC,omitempty"`
	PhoneNumber string `protobuf:"bytes,2,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	Lang        string `protobuf:"bytes,3,opt,name=Lang,proto3" json:"Lang,omitempty"`
}

func (x *UserCreationReq) Reset() {
	*x = UserCreationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_luser_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCreationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreationReq) ProtoMessage() {}

func (x *UserCreationReq) ProtoReflect() protoreflect.Message {
	mi := &file_luser_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreationReq.ProtoReflect.Descriptor instead.
func (*UserCreationReq) Descriptor() ([]byte, []int) {
	return file_luser_service_proto_rawDescGZIP(), []int{0}
}

func (x *UserCreationReq) GetMCC() string {
	if x != nil {
		return x.MCC
	}
	return ""
}

func (x *UserCreationReq) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserCreationReq) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type UserCreationRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	IsFound bool   `protobuf:"varint,2,opt,name=IsFound,proto3" json:"IsFound,omitempty"`
}

func (x *UserCreationRsp) Reset() {
	*x = UserCreationRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_luser_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCreationRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreationRsp) ProtoMessage() {}

func (x *UserCreationRsp) ProtoReflect() protoreflect.Message {
	mi := &file_luser_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreationRsp.ProtoReflect.Descriptor instead.
func (*UserCreationRsp) Descriptor() ([]byte, []int) {
	return file_luser_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserCreationRsp) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UserCreationRsp) GetIsFound() bool {
	if x != nil {
		return x.IsFound
	}
	return false
}

type FindUserByUserIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *FindUserByUserIDReq) Reset() {
	*x = FindUserByUserIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_luser_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindUserByUserIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserByUserIDReq) ProtoMessage() {}

func (x *FindUserByUserIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_luser_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserByUserIDReq.ProtoReflect.Descriptor instead.
func (*FindUserByUserIDReq) Descriptor() ([]byte, []int) {
	return file_luser_service_proto_rawDescGZIP(), []int{2}
}

func (x *FindUserByUserIDReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type FindUserByUserIDRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsFound bool  `protobuf:"varint,1,opt,name=IsFound,proto3" json:"IsFound,omitempty"`
	User    *User `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
}

func (x *FindUserByUserIDRsp) Reset() {
	*x = FindUserByUserIDRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_luser_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindUserByUserIDRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserByUserIDRsp) ProtoMessage() {}

func (x *FindUserByUserIDRsp) ProtoReflect() protoreflect.Message {
	mi := &file_luser_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserByUserIDRsp.ProtoReflect.Descriptor instead.
func (*FindUserByUserIDRsp) Descriptor() ([]byte, []int) {
	return file_luser_service_proto_rawDescGZIP(), []int{3}
}

func (x *FindUserByUserIDRsp) GetIsFound() bool {
	if x != nil {
		return x.IsFound
	}
	return false
}

func (x *FindUserByUserIDRsp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_luser_service_proto protoreflect.FileDescriptor

var file_luser_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6c, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x6c,
	0x75, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x59, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x43, 0x43, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x4d, 0x43, 0x43, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x61, 0x6e, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4c, 0x61, 0x6e, 0x67, 0x22, 0x3b, 0x0a, 0x0f, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x18, 0x0a,
	0x07, 0x49, 0x73, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x49, 0x73, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x2d, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x50, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x55, 0x73,
	0x65, 0x72, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x49, 0x73, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x49, 0x73, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1f, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6c, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x04, 0x55, 0x73, 0x65, 0x72, 0x32, 0x9d, 0x01, 0x0a, 0x05, 0x4c, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x46, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x6c, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x1a, 0x16, 0x2e, 0x6c, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x10, 0x46, 0x69,
	0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a,
	0x2e, 0x6c, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x42,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x6c, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x52, 0x73, 0x70, 0x22, 0x00, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x79, 0x65, 0x72, 0x79, 0x61, 0x6e, 0x2f, 0x6c,
	0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x6f, 0x2f, 0x6c, 0x75, 0x73,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_luser_service_proto_rawDescOnce sync.Once
	file_luser_service_proto_rawDescData = file_luser_service_proto_rawDesc
)

func file_luser_service_proto_rawDescGZIP() []byte {
	file_luser_service_proto_rawDescOnce.Do(func() {
		file_luser_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_luser_service_proto_rawDescData)
	})
	return file_luser_service_proto_rawDescData
}

var file_luser_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_luser_service_proto_goTypes = []interface{}{
	(*UserCreationReq)(nil),     // 0: luser.UserCreationReq
	(*UserCreationRsp)(nil),     // 1: luser.UserCreationRsp
	(*FindUserByUserIDReq)(nil), // 2: luser.FindUserByUserIDReq
	(*FindUserByUserIDRsp)(nil), // 3: luser.FindUserByUserIDRsp
	(*User)(nil),                // 4: luser.User
}
var file_luser_service_proto_depIdxs = []int32{
	4, // 0: luser.FindUserByUserIDRsp.User:type_name -> luser.User
	0, // 1: luser.LUser.GetOrCreateNewUser:input_type -> luser.UserCreationReq
	2, // 2: luser.LUser.FindUserByUserID:input_type -> luser.FindUserByUserIDReq
	1, // 3: luser.LUser.GetOrCreateNewUser:output_type -> luser.UserCreationRsp
	3, // 4: luser.LUser.FindUserByUserID:output_type -> luser.FindUserByUserIDRsp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_luser_service_proto_init() }
func file_luser_service_proto_init() {
	if File_luser_service_proto != nil {
		return
	}
	file_luser_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_luser_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCreationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_luser_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCreationRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_luser_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindUserByUserIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_luser_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindUserByUserIDRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_luser_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_luser_service_proto_goTypes,
		DependencyIndexes: file_luser_service_proto_depIdxs,
		MessageInfos:      file_luser_service_proto_msgTypes,
	}.Build()
	File_luser_service_proto = out.File
	file_luser_service_proto_rawDesc = nil
	file_luser_service_proto_goTypes = nil
	file_luser_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LUserClient is the client API for LUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LUserClient interface {
	GetOrCreateNewUser(ctx context.Context, in *UserCreationReq, opts ...grpc.CallOption) (*UserCreationRsp, error)
	FindUserByUserID(ctx context.Context, in *FindUserByUserIDReq, opts ...grpc.CallOption) (*FindUserByUserIDRsp, error)
}

type lUserClient struct {
	cc grpc.ClientConnInterface
}

func NewLUserClient(cc grpc.ClientConnInterface) LUserClient {
	return &lUserClient{cc}
}

func (c *lUserClient) GetOrCreateNewUser(ctx context.Context, in *UserCreationReq, opts ...grpc.CallOption) (*UserCreationRsp, error) {
	out := new(UserCreationRsp)
	err := c.cc.Invoke(ctx, "/luser.LUser/GetOrCreateNewUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lUserClient) FindUserByUserID(ctx context.Context, in *FindUserByUserIDReq, opts ...grpc.CallOption) (*FindUserByUserIDRsp, error) {
	out := new(FindUserByUserIDRsp)
	err := c.cc.Invoke(ctx, "/luser.LUser/FindUserByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LUserServer is the server API for LUser service.
type LUserServer interface {
	GetOrCreateNewUser(context.Context, *UserCreationReq) (*UserCreationRsp, error)
	FindUserByUserID(context.Context, *FindUserByUserIDReq) (*FindUserByUserIDRsp, error)
}

// UnimplementedLUserServer can be embedded to have forward compatible implementations.
type UnimplementedLUserServer struct {
}

func (*UnimplementedLUserServer) GetOrCreateNewUser(context.Context, *UserCreationReq) (*UserCreationRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrCreateNewUser not implemented")
}
func (*UnimplementedLUserServer) FindUserByUserID(context.Context, *FindUserByUserIDReq) (*FindUserByUserIDRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindUserByUserID not implemented")
}

func RegisterLUserServer(s *grpc.Server, srv LUserServer) {
	s.RegisterService(&_LUser_serviceDesc, srv)
}

func _LUser_GetOrCreateNewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LUserServer).GetOrCreateNewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/luser.LUser/GetOrCreateNewUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LUserServer).GetOrCreateNewUser(ctx, req.(*UserCreationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LUser_FindUserByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserByUserIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LUserServer).FindUserByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/luser.LUser/FindUserByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LUserServer).FindUserByUserID(ctx, req.(*FindUserByUserIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _LUser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "luser.LUser",
	HandlerType: (*LUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrCreateNewUser",
			Handler:    _LUser_GetOrCreateNewUser_Handler,
		},
		{
			MethodName: "FindUserByUserID",
			Handler:    _LUser_FindUserByUserID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "luser/service.proto",
}
