// Code generated by protoc-gen-go. DO NOT EDIT.
// source: errors/service.proto

package errors // import "github.com/tyeryan/l-protocol/go/errors"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Caller struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	FuncName             string   `protobuf:"bytes,2,opt,name=FuncName,proto3" json:"FuncName,omitempty"`
	FileName             string   `protobuf:"bytes,3,opt,name=FileName,proto3" json:"FileName,omitempty"`
	LineNum              int32    `protobuf:"varint,4,opt,name=lineNum,proto3" json:"lineNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Caller) Reset()         { *m = Caller{} }
func (m *Caller) String() string { return proto.CompactTextString(m) }
func (*Caller) ProtoMessage()    {}
func (*Caller) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_c1f69c980023abc7, []int{0}
}
func (m *Caller) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Caller.Unmarshal(m, b)
}
func (m *Caller) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Caller.Marshal(b, m, deterministic)
}
func (dst *Caller) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Caller.Merge(dst, src)
}
func (m *Caller) XXX_Size() int {
	return xxx_messageInfo_Caller.Size(m)
}
func (m *Caller) XXX_DiscardUnknown() {
	xxx_messageInfo_Caller.DiscardUnknown(m)
}

var xxx_messageInfo_Caller proto.InternalMessageInfo

func (m *Caller) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Caller) GetFuncName() string {
	if m != nil {
		return m.FuncName
	}
	return ""
}

func (m *Caller) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *Caller) GetLineNum() int32 {
	if m != nil {
		return m.LineNum
	}
	return 0
}

type ErrorDetail struct {
	Stan                 string   `protobuf:"bytes,1,opt,name=Stan,proto3" json:"Stan,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	GrpcCode             uint32   `protobuf:"varint,3,opt,name=GrpcCode,proto3" json:"GrpcCode,omitempty"`
	Desc                 string   `protobuf:"bytes,4,opt,name=Desc,proto3" json:"Desc,omitempty"`
	Error                string   `protobuf:"bytes,5,opt,name=Error,proto3" json:"Error,omitempty"`
	CallerInfo           *Caller  `protobuf:"bytes,6,opt,name=CallerInfo,proto3" json:"CallerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorDetail) Reset()         { *m = ErrorDetail{} }
func (m *ErrorDetail) String() string { return proto.CompactTextString(m) }
func (*ErrorDetail) ProtoMessage()    {}
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_c1f69c980023abc7, []int{1}
}
func (m *ErrorDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorDetail.Unmarshal(m, b)
}
func (m *ErrorDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorDetail.Marshal(b, m, deterministic)
}
func (dst *ErrorDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorDetail.Merge(dst, src)
}
func (m *ErrorDetail) XXX_Size() int {
	return xxx_messageInfo_ErrorDetail.Size(m)
}
func (m *ErrorDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorDetail proto.InternalMessageInfo

func (m *ErrorDetail) GetStan() string {
	if m != nil {
		return m.Stan
	}
	return ""
}

func (m *ErrorDetail) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ErrorDetail) GetGrpcCode() uint32 {
	if m != nil {
		return m.GrpcCode
	}
	return 0
}

func (m *ErrorDetail) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ErrorDetail) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ErrorDetail) GetCallerInfo() *Caller {
	if m != nil {
		return m.CallerInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*Caller)(nil), "errors.Caller")
	proto.RegisterType((*ErrorDetail)(nil), "errors.ErrorDetail")
}

func init() { proto.RegisterFile("errors/service.proto", fileDescriptor_service_c1f69c980023abc7) }

var fileDescriptor_service_c1f69c980023abc7 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0xc7, 0x15, 0x68, 0x02, 0xbd, 0x08, 0x06, 0xab, 0x83, 0xc5, 0x14, 0x75, 0x21, 0x0c, 0xd8,
	0x12, 0xbc, 0x01, 0x2d, 0x20, 0x96, 0x0e, 0xee, 0xc6, 0xe6, 0x1a, 0x53, 0x2c, 0x39, 0x76, 0xe5,
	0x38, 0x48, 0x95, 0x78, 0x23, 0x5e, 0xb2, 0xf2, 0x39, 0xad, 0xba, 0xdd, 0xff, 0xe3, 0xf4, 0xb3,
	0x0f, 0x66, 0x3a, 0x04, 0x1f, 0x7a, 0xde, 0xeb, 0xf0, 0x6b, 0x94, 0x66, 0xbb, 0xe0, 0xa3, 0x27,
	0x55, 0x76, 0xe7, 0x7f, 0x50, 0x2d, 0xa4, 0xb5, 0x3a, 0x90, 0x06, 0xea, 0x75, 0xae, 0xac, 0x64,
	0xa7, 0x69, 0xd1, 0x14, 0xed, 0x54, 0x9c, 0x5b, 0xe4, 0x0e, 0xae, 0xdf, 0x06, 0xa7, 0x30, 0xbe,
	0xc0, 0xf8, 0xa4, 0x31, 0x33, 0x36, 0xaf, 0x5e, 0x8e, 0xd9, 0xa8, 0x09, 0x85, 0x2b, 0x6b, 0x9c,
	0x5e, 0x0d, 0x1d, 0x9d, 0x34, 0x45, 0x5b, 0x8a, 0xa3, 0x9c, 0xff, 0x17, 0x50, 0xbf, 0xa6, 0x87,
	0x2c, 0x75, 0x94, 0xc6, 0x12, 0x02, 0x93, 0x75, 0x94, 0x6e, 0x84, 0xe3, 0x9c, 0xbc, 0x85, 0xff,
	0x3a, 0x12, 0x71, 0x4e, 0xb4, 0xf7, 0xb0, 0x53, 0xe8, 0x27, 0xda, 0x8d, 0x38, 0xe9, 0xd4, 0x5f,
	0xea, 0x5e, 0x21, 0x6a, 0x2a, 0x70, 0x26, 0x33, 0x28, 0x11, 0x43, 0x4b, 0x34, 0xb3, 0x20, 0x0c,
	0x20, 0xff, 0xfd, 0xc3, 0x7d, 0x7b, 0x5a, 0x35, 0x45, 0x5b, 0x3f, 0xdd, 0xb2, 0x7c, 0x18, 0x96,
	0x13, 0x71, 0xd6, 0x78, 0x79, 0xf8, 0xbc, 0xdf, 0x9a, 0xf8, 0x33, 0x6c, 0x98, 0xf2, 0x1d, 0x8f,
	0x7b, 0x1d, 0xf6, 0xd2, 0x71, 0xfb, 0x88, 0x17, 0x55, 0xde, 0xf2, 0xad, 0xe7, 0x79, 0x7b, 0x53,
	0xa1, 0xf7, 0x7c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x0f, 0xdc, 0xbc, 0x7d, 0x01, 0x00, 0x00,
}
